fix: border-color dos inputs resolvido
danielsaviosec/marte-101-sistema pull request #1
Opened 2023-10-20 00:55 UTC by victor-ferreira-dev

2023-10-20 01:02 UTC, victor-ferreira-dev commented
![](https://github.trello.services/images/mini-trello-icon.png) [[MARTE 101] Login 01 - Criação da Página Estática (Sem interação)](https://trello.com/c/y46YHLGU/203-marte-101-login-01-cria%C3%A7%C3%A3o-da-p%C3%A1gina-est%C3%A1tica-sem-intera%C3%A7%C3%A3o)

2023-10-21 16:19 UTC, danielsaviosec requested changes

2023-10-21 16:19 UTC, danielsaviosec commented on src/app/pages/login/login.component.ts
> +	primary = '#ffffff';
o que seria esse primary?

2023-10-21 17:17 UTC, victor-ferreira-dev commented on src/app/pages/login/login.component.ts
> +	primary = '#ffffff';
De quando estava testando os theme colors do Angular, esqueci de deletar essa linha...

2023-10-25 01:03 UTC, merged