style(pages): estilização da recover-password page
danielsaviosec/marte-101-sistema pull request #2
Opened 2023-10-23 21:41 UTC by victor-ferreira-dev

2023-10-26 13:48 UTC, victor-ferreira-dev commented
![](https://github.trello.services/images/mini-trello-icon.png) [[MARTE 101] Recuperação de Senha 02 - Página de recuperação: campo e-mail e botão enviar](https://trello.com/c/U8jyh1oI/253-marte-101-recupera%C3%A7%C3%A3o-de-senha-02-p%C3%A1gina-de-recupera%C3%A7%C3%A3o-campo-e-mail-e-bot%C3%A3o-enviar)

2023-10-27 19:35 UTC, danielsaviosec requested changes
Nao pode subir suas alteracoes junto da Diego

2023-10-27 19:35 UTC, danielsaviosec commented on src/app/pages/login/login.component.scss
> +    //     width: 60%;
remover comentarios

2023-10-27 19:35 UTC, danielsaviosec commented on src/app/pages/login/login.component.ts
> +	onSubmit()  {
faltou documentar

2023-10-27 19:35 UTC, danielsaviosec commented on src/app/pages/recover-password/recover-password.component.ts
> +	goToLogin() {
faltou tipagem do retorno

2023-10-31 20:59 UTC, closed without merging