feat(new-pw): estrutura + validações
danielsaviosec/marte-101-sistema pull request #4
Opened 2023-11-02 00:14 UTC by victor-ferreira-dev

2023-11-02 00:17 UTC, victor-ferreira-dev commented
![](https://github.trello.services/images/mini-trello-icon.png) [[MARTE 101] Página de Nova Senha \ New-Password](https://trello.com/c/xc7irLRm/469-marte-101-p%C3%A1gina-de-nova-senha-new-password)

2023-11-06 20:07 UTC, danielsaviosec requested changes

2023-11-06 20:07 UTC, danielsaviosec commented on src/app/pages/new-password/new-password.component.ts
> +		console.log(this.newPasswordForm.value);
remover console.log()

2023-11-06 20:07 UTC, danielsaviosec commented on src/app/pages/new-password/new-password.component.ts
> +			const newPassword = control.get('newPassword')?.value;
faltou tipagem

2023-11-06 20:07 UTC, danielsaviosec commented on src/app/pages/new-password/new-password.component.ts
> +			const confirmPassword = control.get('confirmPassword')?.value;
faltou tipagem

2023-11-09 00:53 UTC, danielsaviosec approved these changes

2023-11-09 00:53 UTC, merged