feat(recover-pw): validação do email + submit
danielsaviosec/marte-101-sistema pull request #5
Opened 2023-11-02 02:48 UTC by victor-ferreira-dev

2023-11-02 02:49 UTC, victor-ferreira-dev commented
![](https://github.trello.services/images/mini-trello-icon.png) [[MARTE 101] Recuperação de Senha 02 - Página de recuperação: campo e-mail e botão enviar](https://trello.com/c/U8jyh1oI/253-marte-101-recupera%C3%A7%C3%A3o-de-senha-02-p%C3%A1gina-de-recupera%C3%A7%C3%A3o-campo-e-mail-e-bot%C3%A3o-enviar)

2023-11-06 20:08 UTC, danielsaviosec requested changes

2023-11-06 20:08 UTC, danielsaviosec commented on src/app/pages/recover-password/recover-password.component.ts
> +		console.log(this.recoverForm.value);
remover console.log

2023-11-09 00:54 UTC, danielsaviosec approved these changes

2023-11-09 00:54 UTC, danielsaviosec requested changes
ajustar conflitos

2023-11-09 01:16 UTC, danielsaviosec approved these changes

2023-11-09 01:17 UTC, merged