feat(modal): services & toggle method
danielsaviosec/marte-101-sistema pull request #7
Opened 2023-11-02 05:12 UTC by victor-ferreira-dev

2023-11-02 05:13 UTC, victor-ferreira-dev commented
![](https://github.trello.services/images/mini-trello-icon.png) [[MARTE 101] Recuperação de Senha 03 - Pop-Up de e-mail enviado (Modal)](https://trello.com/c/sIalYtoR/254-marte-101-recupera%C3%A7%C3%A3o-de-senha-03-pop-up-de-e-mail-enviado-modal)

2023-11-06 20:07 UTC, danielsaviosec requested changes

2023-11-06 20:07 UTC, danielsaviosec commented on src/app/services/window.service.ts
> +	private isOpenSubject = new BehaviorSubject<boolean>(false);
faltou tipagem

2023-11-06 20:07 UTC, danielsaviosec commented on src/app/components/success-window/success-window.component.ts
> +	WindowIsOpen = false;
faltou tipagem

2023-11-06 20:07 UTC, danielsaviosec commented on src/app/components/success-window/success-window.component.ts
> +	@Input() description = '';
faltou tipagem

2023-11-06 20:07 UTC, danielsaviosec commented on src/app/components/success-window/success-window.component.ts
> +	WindowIsOpen = false;
faltou modificador de acesso, nome da variável nao começa com letra maiúscula

2023-11-09 01:20 UTC, danielsaviosec approved these changes

2023-11-09 01:20 UTC, merged